### ISSUE TITLE
Is there any way to enable https access?

### ISSUE THREAD

**Issue by pimgeek** [OokTech/TW5-BobEXE#1]
I have secured my blog and other nodejs app with https, by letsencrypt certbot script, so I have got the necessary https certificates. My question is can I enable https access to BobLinux？ 😃

**Comment by pimgeek** [comment]
I figured it out myself: 

suppose apache is already https-secured.

1. launch BobLinux locally, say http://localhost:8080  
2. setup apache reverse proxy  
```
    ProxyPass               /tw     http://localhost:8080/
    ProxyPassReverse        /tw     http://localhost:8080/
```
3. restart apache service 
4. access BobLinux via https://mydomain/tw

**Comment by inmysocks** [comment]
I have a solution to running Bob with https using Node that you may be interested in. It is what is running the wikis on ooktech.xyz and handling the login and access control there. I am hoping to release the code for it today. The part that is holding me back from releasing it is documentation, which is very incomplete but parts are available here https://www.ooktech.xyz:8443/SecureNodeServer

I am going the check over the repo to make sure that there aren't any parts of the documentation that are completely wrong and then release it and update it as I have time.
