### ISSUE TITLE
Bob-win.Exe on Windows: A red area like a ribbon bottom of window blinks

### ISSUE THREAD

**Issue by kookma** [OokTech/TW5-BobEXE#15]
Many thanks for new update hy!
The new Bobexe works fine on Windows.

Minor issue
When you run Bobwin.exe on Windows / Chrome 81
It fires Chrome and opens a wiki, a red area blinks and appears at the bottom of screen and disappears.

**Comment by inmysocks** [comment]
That is not a bug.
After the wiki opens it has to connect to the node backend and before that happens there is a red warning ribbon at the bottom telling you it isn't connected.

**Comment by kookma** [comment]
That's true jed!
May be if  Jed can check this a bit later (in the code) or if a few seconds wait and then throw the red message, resolve this short blinking.
