### ISSUE TITLE
Error: Unknown command: wsserver

### ISSUE THREAD

**Issue by newhinton** [OokTech/TW5-BobEXE#2]
I have encountered the problem that the executables wont start after i compiled them. 
I have tried to compile Tiddlywiki5 5.1.17 (and the latest version from github) to win64. Is there anything im missing?

**Comment by inmysocks** [comment]
Did you initialise the submodules for the plugins?

**Comment by newhinton** [comment]
Do you mean "Bob" and "TWederBob"?
I have downloaded the zip's from the corresponding repositories, but besides from that i just used the buildscript (and later moved the pkg command to the scripts section of the package.json and executed "npm run build").

Did i forget something?

Although i think that it would be cool if your script would work without the submodules, but thats fine :)

**Comment by inmysocks** [comment]
The point of sub-modules is that Bob, TiddlyWiki and TWederBob are developed independently and using submodules means that I don't have to do a lot of copying and pasting whenever I update Bob.

If you don't want to modify anything just download the binaries from the releases.

It being cool if the script could work without submodules means more work for me and I am unclear about what the benefit would be. If you want to use the executables without modifying anything than just download the executables, if you want to modify something than the submodules make that significantly easier to do.

So what is your goal?

**Comment by inmysocks** [comment]
I am also confused about why you downloaded zip's. I don't know what you are trying to do with that part.

**Comment by newhinton** [comment]
My goal is to build custom versions with my own plugins, but that is the second step. My first step is to rebuild your version, without any modification (to understand how you did it and how it works)

Instead of git clone "yourplugins" i went to the corresponding git-repositories and downloaded the latest sources as a zip file, and unpacked them in their folders, wich should effectively be the same, except i am mistaken here

**Comment by inmysocks** [comment]
Look up git submodules to understand that part. The only plugin that is necessary is Bob in the plugins/OokTech folder.

Then add any other plugins you want to the plugins folder like they were normal plugins and you can change what is in the editions/Bob wiki to change the default index wiki.

You can put themes and editions into the themes and editions folders to make them available to the wikis created using Bob.

You should probably change the output executable name too to avoid confusion with other versions.

**Comment by inmysocks** [comment]
https://github.com/OokTech/TW5-BobEXE/tree/master/plugins/OokTech

**Comment by inmysocks** [comment]
I removed and re-added all of the submodules so hopefully it works for you now.

This may be helpful for future issues: https://www.ooktech.xyz:8443/Public#How%20to%20make%20a%20good%20feature%20request
