### ISSUE TITLE
Issue: Serving Files #1 - mimeMap not on in deafult

### ISSUE THREAD

**Issue by TiddlyTweeter** [OokTech/TW5-BobEXE#5]
At the moment on Bob executable 1.0.6 the default "mimeMap" does not seem to be automatically loaded.

I needed to create manual entries in Manual Settings to enable the files to display. I tested this for both ".jpg" and ".png" types. Neither worked until I set the mime type manually.

**Comment by TiddlyTweeter** [comment]
How is this Off Topic?

Am I incorrect? Which I could be. The mimeMap wasn't working. 

Your closing of my recent issues is okay. Some are more exploratory than directly helpful.

**Comment by inmysocks** [comment]
This is off topic because this isn't the Bob repo.

**Comment by TiddlyTweeter** [comment]
Do you mean I should have posted those a different place?

**Comment by TiddlyTweeter** [comment]
PLEASE make that clear on GG.

From my point of view where I GET the working thing from is WHERE I
respond. Why not?

I am not a mind reader. And your actions caused me distress, thinking you
disliked my posts.

I better see now you are tidying administration. Great. Just don't trash
stuff without explanation.

Josiah

**Comment by TiddlyTweeter** [comment]
I will re-read you flag of "Off-Topic" as "In The Wrong Place" and start
again.
